### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jonpas** [sqwishy/vim-sqf-syntax#2]
This project has no license, so it's not easy to derive from it, especially if you stop updating it. Would be nice to add one (MIT ;) ).

**Comment by sqwishy** [comment]
Is WTFPL fine?

**Comment by jonpas** [comment]
It's your project. :P

I personally would never use that when MIT exists and is actually supported, backed and widely used.

**Comment by sqwishy** [comment]
But it has a funny sounding name. Will the WTFPL prevent you from doing what you want to do with it?

**Comment by jonpas** [comment]
No, nothing special I want, just pointing out that there is no license.

**Comment by sqwishy** [comment]
Okay cool, thanks.
